@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Oct 16 22:24:10 -0700 2023
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_control_unit_behav -key {Behavioral:sim_1:Functional:tb_control_unit} -tclbatch tb_control_unit.tcl -view C:/Users/lbell/Network-Microprocessor-FPGA-Project/Network-Microprocessor-FPGA-Project/SingleCycle/SingleCycle.ip_user_files/tb_reg_file_behav.wcfg -view C:/Users/lbell/Network-Microprocessor-FPGA-Project/Network-Microprocessor-FPGA-Project/SingleCycle/SingleCycle.ip_user_files/tb_instru_mem_behav.wcfg -view C:/Users/lbell/Network-Microprocessor-FPGA-Project/Network-Microprocessor-FPGA-Project/SingleCycle/SingleCycle.ip_user_files/tb_control_unit_behav.wcfg -log simulate.log"
call xsim  tb_control_unit_behav -key {Behavioral:sim_1:Functional:tb_control_unit} -tclbatch tb_control_unit.tcl -view C:/Users/lbell/Network-Microprocessor-FPGA-Project/Network-Microprocessor-FPGA-Project/SingleCycle/SingleCycle.ip_user_files/tb_reg_file_behav.wcfg -view C:/Users/lbell/Network-Microprocessor-FPGA-Project/Network-Microprocessor-FPGA-Project/SingleCycle/SingleCycle.ip_user_files/tb_instru_mem_behav.wcfg -view C:/Users/lbell/Network-Microprocessor-FPGA-Project/Network-Microprocessor-FPGA-Project/SingleCycle/SingleCycle.ip_user_files/tb_control_unit_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
